version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "teslabot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pcatkpeq1n2w"
s3_prefix = "teslabot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["SentimentFunction=681261969843.dkr.ecr.us-east-1.amazonaws.com/teslabot6cc6bd50/sentimentfunction35d37012repo"]
